### ISSUE TITLE
(Minor) 질문, 프로필 소득운영현황 라디오버튼->체크박스

### ISSUE THREAD

**Issue by clearbean** [PLAY-LAB/sky-cherry#128]
**Level**
Minor

**Describe the bug**
질문, 프로필 입력 시 소득운영현황 라디오버튼에서 체크박스로 변경

**Comment by rygh4775** [comment]
@clearbean 해당 변경 사항 발생시, DB 데이터를 초기화해야 합니다.. 참고하시라고 미리 알려드립니다.

**Comment by clearbean** [comment]
@rygh4775 슬랙에 남겨두었는데 DB데이터 초기화 이슈로 해당 이슈 수정 없이 closing 부탁 드립니다!
