### ISSUE TITLE
(Major) 프로필 저장 시 반영 안됨

### ISSUE THREAD

**Issue by clearbean** [PLAY-LAB/sky-cherry#132]
**Level**
Major

**Describe the bug**
프로필 수정 후 저장 시 체리만 부여되고 프로필 반영이 안됩니다.

**Comment by rygh4775** [comment]
@clearbean 재현이 되지 않고 있습니다.
증상 재현되는지 확인 해주시고, 발생시 sky-cherry 구동시킨 콘솔창에 있는 로그내용을 첨부 부탁드리겠습니다.

**Comment by clearbean** [comment]
저도 재현이 안되네요.. 해당 이슈 클로징 부탁드리며 재현 시 다시 오픈하겠습니다.
