### ISSUE TITLE
Sky Cherry 업데이트 가이드 (Windows)

### ISSUE THREAD

**Issue by rygh4775** [PLAY-LAB/sky-cherry#149]
* sky-cherry 새로운 버전 설치(업데이트)
* 업데이트 정상 처리 확인 방법
* DB 스키마 변경시 처리 방법

**Comment by clghks** [comment]
Wiki에 업데이트 방법 추가 
[Sky Cherry 새로운 버전 설치 (업데이트)
](https://github.com/PLAY-LAB/sky-cherry/wiki/Sky-Cherry-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%B2%84%EC%A0%84-%EC%84%A4%EC%B9%98-(%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8))
