### ISSUE TITLE
메뉴얼 작성

### ISSUE THREAD

**Issue by clghks** [PLAY-LAB/sky-cherry#74]
- 설치 메뉴얼 작성

**Comment by rygh4775** [comment]
* 상대 경로 -> 절대 경로 수정
* 윈도우에서 에러 발생시 package.json에 DEBUG~ 제거 내용 추가

**Comment by rygh4775** [comment]
@clghks 
몽고DB 클라이언트 설치 및 사용법 작성 추가해주세요.

**Comment by clghks** [comment]
@rygh4775 
- 몽고DB 설치 방법 추가 했습니다. 
https://github.com/PLAY-LAB/sky-cherry/issues/108
- 상대 경로 -> 절대 경로 수정 완료 
- DEBUG 옵션은 master로 옴길때 제거 예정

**Comment by rygh4775** [comment]
@clghks 
* DEBUG 옵션을 제거 하실 예정이면, develope 브랜치에서 제거 하는게 좋을 것 같습니다. (제거했을 때, 어떤 변경 사항이 발생하는지 미리 체크)

**Comment by clghks** [comment]
@rygh4775 
- Debug 옵션 제거 하였습니다. [#115](https://github.com/PLAY-LAB/sky-cherry/pull/115)
- Robo 3T 사용하여 이름, 나이, 성별 수정하는 예제 추가 하였습니다. [#112](https://github.com/PLAY-LAB/sky-cherry/issues/112)
